In [10]:
import os
import pandas as pd
import re

In [29]:
import nltk

In [42]:
import random
from random import randint

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [23]:
pd.options.display.max_rows = None

In [2]:
path = '/Users/hernanadasme/Projects/estadio_1940_1980/estadio_pdfs/clean_txts_1958_2'

In [3]:
# read all txt files in the directory into a list of strings
txt_list = []
for file in os.listdir(path):
    if file.endswith('.txt'):
        with open(os.path.join(path, file), 'r') as f:
            txt_list.append(f.read())

In [5]:
# create a pandas DataFrame with one row per txt file
df_es_1958 = pd.DataFrame({'page_text': txt_list})

In [1]:
df_es_1958

NameError: name 'df_es_1958' is not defined

In [18]:
# define preprocessing function
def preprocess_text(text):
    # convert text to lowercase
    text = text.lower()
    # remove special characters
    text = re.sub(r'[^\w\s]','',text)
    # remove numbers
    text = re.sub(r'\d+', '', text)
    text = ' '.join([word for word in text.split() if len(word) > 1])
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', text)
    # remove _ characters
    text = text.replace('_', '')
    # remove whitespace
    text = re.sub(r'\s+', ' ', text)
    
    return text

In [19]:
# apply preprocessing function to text column
df_es_1958['page_text'] = df_es_1958['page_text'].apply(lambda x: preprocess_text(x))

In [24]:
df_es_1958

page_text
0    potentes seguras económicas más barata económi...
1     ss sí jn cuatro días universidad católicaprod...
2    deténgalocon ar zl viene delapagevio más armad...
3    oelviernes rí selsábado viajessintrasbordo de ...
4    juntoalloroquelerecuerda sus no chesdegloria j...
5    levanta los brazosalborozado juan zamoranoalll...
6                          aasa sá iü sf viisas nnfirm
7                        my hsr ttll eí eá wi iim sjrm
8    lapenade mc donald unamigode yugoslavia quétie...
9    fuedegranespectáculo el gol de mario moreno re...
10   twa dante gianoni quefue siempre incisivotomau...
11   san pablo casilla fono santiago humberto sáeze...
12                                                    
13   muy concurridoestedelesquí chileno queacabadee...
14   ingresa alring sergio salviaysurivallevanta la...
15   perjudicó aunpeleador chileno queporloquellevo...
16   ffiov uv fú en lonareforzados tamaño corriente...
17   venedelapag tantebienaunque sinestablecer sulí...
18   mundial quegozódetantapopularidadyquemerecióta...
19        mé iéotho pm tó jvívpí vv hf ifcáiwa mivowmá
20   sólo dosencandelero posibilidades serenenses u...
21   magnífica actuación de hernán delgadopromisori...
22   tobar tuvouncentinela iplacableen almeyda losd...
23   lasexigencias cadavez más durasdelosrecorridos...
24   aquienes esté nsiguiendoestecursoselesrecomien...
25   elentrenador del equipo alemán campeóndelmundo...
26   livingstone muchas vecesleescuchéprotestas ter...
27   fú lmmmr francia confirmó sucaracterística sob...
28   sus tijii üiinimuíninimuínuillilllmuí nopinion...
29                                                    
30   eenerode john landyhablapreparado almundo alai...
31   que juan manuel fangio el cinco vecescampeón d...
32   cambiede método eí lé ilrñwlmí áisinhojasinmam...
33   zagalo vavá pelé quién los conocía haceunparde...
34   unhinchamexicano acompañante deladelegaciónves...
35   adeclinación de atagalla nesharestado atractiv...
36   los jóvenes quecomienzan en el deporte rentado...
37   ió esunodenuestros deporte dealtajerarquía int...
38   condoscualidades valiosas rapidez el asticidad...
39   ífifiííiílír wa pocoantesdelaunadelatardedelab...
40   íffimisijvazi eimn bataianimaémmmmamrstt baste...
41   viene delapag lesquedaban todavía minutos para...
42   tí sanos fuertes vigorosostoman estudiajuegatr...
43   llevárselo por delante noloconsiguió aunque ar...
44   losvolantes peruanos tienenmáquinas muy corred...
45   bill tildenfueunverdadero actordeltenis eralaa...
46   lí unaorganización chilenaalserviciodeldepoite...
47   eldesánimo prematuro de green crossrestóelclim...
48   conmadurez técnica no tablefísico vicente vera...
49   ió allcocks ió prácticos tamaños adhiere más m...
50   hernán bolaños no hacambiado lucelallanezaelvi...
51   wmrp enúltimainstancia isaac carrasco lograpun...
52   juegosólidofuertetécnicamente biendotadoyvsist...
53   idá jdá ui mi já má etipodezapatillade científ...
54   acampeón tercero sexto porlasrazonesseñaladas ...
55   oelviernes rí selsábado viajessintrasbordo de ...
56   undíasefueexplicó hoyvuelve aestarconmigo si m...
57   historia tristedeunavidadisparatada quepodrías...
58   apr ui losdos más grandesdecalletasdelmundo ra...
59                                 wai zjírj jg riqzrz
60   otravez fangio laguirnalda delaureles asicomoe...
61   luchan decerca harris patterson en los comienz...
62   meér vm lii hagalapausaquerefrescaconlachispea...
63   lnaquevinoaisudamericano seeode quilo forman l...
64                                                    
65   loqueesunacarrera en monza espectadores rodean...
66   la falta dematerial humano queafectaalremoloha...
67   tiiimijjtm sii bl iíífcst etíio sc sou ot jfl ...
68   deregreso escaparon juan zamorano santibáñez r...
69   verdejo respaldado por gilavanzahaciaoláreapor...
70   floridas no está en suañomedijeron ylie ahí qu...
71   garrincha ídolodelossuecos los esclavos el moi...
72   laimplantación delallamad

**Preprocessing with Count Vectorizer**

In [201]:
# Define a custom list of Spanish stopwords
spanish_stopwords = nltk.corpus.stopwords.words('spanish')

In [292]:
spanish_stopwords

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosotros',
 'vosotras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestro'

In [203]:
# define the list of vowels
vowels = ['a', 'e', 'i', 'o', 'u', 'á', 'é', 'í', 'ó', 'ú']
combinations = [''.join(comb) for comb in itertools.product(vowels, repeat=2)]
combinations

['aa',
 'ae',
 'ai',
 'ao',
 'au',
 'aá',
 'aé',
 'aí',
 'aó',
 'aú',
 'ea',
 'ee',
 'ei',
 'eo',
 'eu',
 'eá',
 'eé',
 'eí',
 'eó',
 'eú',
 'ia',
 'ie',
 'ii',
 'io',
 'iu',
 'iá',
 'ié',
 'ií',
 'ió',
 'iú',
 'oa',
 'oe',
 'oi',
 'oo',
 'ou',
 'oá',
 'oé',
 'oí',
 'oó',
 'oú',
 'ua',
 'ue',
 'ui',
 'uo',
 'uu',
 'uá',
 'ué',
 'uí',
 'uó',
 'uú',
 'áa',
 'áe',
 'ái',
 'áo',
 'áu',
 'áá',
 'áé',
 'áí',
 'áó',
 'áú',
 'éa',
 'ée',
 'éi',
 'éo',
 'éu',
 'éá',
 'éé',
 'éí',
 'éó',
 'éú',
 'ía',
 'íe',
 'íi',
 'ío',
 'íu',
 'íá',
 'íé',
 'íí',
 'íó',
 'íú',
 'óa',
 'óe',
 'ói',
 'óo',
 'óu',
 'óá',
 'óé',
 'óí',
 'óó',
 'óú',
 'úa',
 'úe',
 'úi',
 'úo',
 'úu',
 'úá',
 'úé',
 'úí',
 'úó',
 'úú']

In [228]:
letters = list('abcdefghijklmnopqrstuvwxyz')

# generate all possible combinations of the letters and join them into strings
combinationL = [''.join(comb) for comb in itertools.product(letters, repeat=2)]

In [229]:
combinationL[:10]

['aa', 'ab', 'ac', 'ad', 'ae', 'af', 'ag', 'ah', 'ai', 'aj']

In [416]:
list_of_junk = ['fú','guayos', 'conun', 'ca', 'an', 'ados', 'ba', 'aeste', 
                'bí', 'bl', 'aotro', 'jo', 'enel', 'as', 'ael', 'aba', 'aese', 'aios', 'delos', 'dela', 'alladode', 'cadauna', 'cadauno', 'aiul', 'sólo']

In [417]:
# iterate over the original list, add one to each element, and append the updated element to the new list
for word in combinations:
    if word not in spanish_stopwords:
        spanish_stopwords.append(word)
for word in list_of_junk:
    if word not in spanish_stopwords:
        spanish_stopwords.append(word)
for word in combinationL:
    if word not in spanish_stopwords:
        spanish_stopwords.append(word)

**Fit Count Vectorizer**

In [439]:
cv = CountVectorizer(max_df=0.90, min_df=2, stop_words= spanish_stopwords)

In [440]:
dtm = cv.fit_transform(df_es_1958['page_text'])

In [441]:
dtm

<934x14644 sparse matrix of type '<class 'numpy.int64'>'
	with 91316 stored elements in Compressed Sparse Row format>

**Latent Dirilecht Allocation**

In [362]:
from sklearn.decomposition import LatentDirichletAllocation

In [442]:
LDA = LatentDirichletAllocation(n_components=10,random_state=300)

In [443]:
LDA.fit(dtm)

LatentDirichletAllocation(random_state=300)

**Get the Vocabulary of Words**

In [444]:
len(cv.get_feature_names())

14644

In [406]:
type(cv.get_feature_names())

list

In [425]:
cv.get_feature_names()[1000]

'apropiado'

In [403]:
for i in range(40):
    random_word_id = random.randint(0,865)
    print(cv.get_feature_names()[random_word_id])

andaba
aburridos
alolargodelperíodo
ablandó
aguad
acompañante
alto
alareglamentación
ajugado
amucho
amm
alcorazón
aceptó
alacarrera
andaba
andando
altríocentral
allegar
alestadio
aalrededor
alasrudezas
alescribir
alascuerdas
adisposición
adefender
abierta
alfamoso
alevantar
almenos
allá
acolchadoi
alinearon
agosto
acompañado
ando
amplias
altríocentral
alaprueba
alegre
acasoporque


In [382]:
len(LDA.components_)

10

In [446]:
single_topic = LDA.components_[0]

In [447]:
single_topic

array([0.1       , 0.1       , 0.1       , ..., 2.09996188, 0.10001235,
       1.11464603])

In [448]:
single_topic.argsort()[-10:]

array([11244,  9837,  2246,  6896, 13101, 12442, 11843,  6460,  6613,
        7454])

In [449]:
top_word_indices = single_topic.argsort()[-10:]

In [450]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

ramírez
partido
coló
hernán
sé
siempre
san
fútbol
gol
juan


In [451]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 10 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-10:]])
    print('\n')

THE TOP 10 WORDS FOR TOPIC #0
['ramírez', 'partido', 'coló', 'hernán', 'sé', 'siempre', 'san', 'fútbol', 'gol', 'juan']


THE TOP 10 WORDS FOR TOPIC #1
['siempre', 'chile', 'tres', 'deporte', 'partido', 'cancha', 'gol', 'fútbol', 'equipo', 'coló']


THE TOP 10 WORDS FOR TOPIC #2
['gol', 'modelo', 'siempre', 'fútbol', 'pantalón', 'marca', 'onzas', 'guantes', 'juegode', 'camiseta']


THE TOP 10 WORDS FOR TOPIC #3
['años', 'equipo', 'tres', 'chile', 'record', 'gol', 'deporte', 'jugador', 'santiago', 'fútbol']


THE TOP 10 WORDS FOR TOPIC #4
['cancha', 'brasil', 'suecia', 'mundial', 'partido', 'jugador', 'gol', 'equipo', 'chile', 'fútbol']


THE TOP 10 WORDS FOR TOPIC #5
['jugador', 'santiago', 'siempre', 'wanderers', 'partido', 'fútbol', 'san', 'tres', 'chile', 'gol']


THE TOP 10 WORDS FOR TOPIC #6
['fútbol', 'equipo', 'san', 'defensa', 'tres', 'wanderers', 'coló', 'partido', 'segundo', 'gol']


THE TOP 10 WORDS FOR TOPIC #7
['después', 'años', 'minutos', 'johnson', 'jack', 'siempre', 't

**Classify our Text with the topics**

In [452]:
dtm

<934x14644 sparse matrix of type '<class 'numpy.int64'>'
	with 91316 stored elements in Compressed Sparse Row format>

In [453]:
topic_results = LDA.transform(dtm)

In [454]:
topic_results.shape

(934, 10)

In [456]:
topic_results[1].round(2)

array([0.  , 0.97, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

**Combining into one single dataframe**

In [457]:
topic_results.argmax(axis=1)

array([2, 1, 7, 6, 5, 0, 3, 0, 3, 6, 8, 8, 0, 2, 2, 9, 3, 9, 4, 0, 6, 0,
       6, 8, 2, 8, 4, 4, 3, 0, 7, 6, 5, 4, 5, 7, 6, 8, 2, 0, 6, 2, 9, 2,
       1, 2, 3, 1, 8, 5, 0, 1, 4, 1, 7, 6, 6, 5, 8, 0, 8, 4, 5, 4, 0, 8,
       8, 1, 0, 1, 6, 6, 5, 2, 0, 4, 8, 9, 1, 6, 0, 6, 6, 4, 6, 7, 6, 6,
       3, 6, 4, 8, 5, 7, 7, 6, 1, 6, 2, 0, 0, 4, 2, 1, 6, 0, 6, 2, 1, 4,
       2, 0, 9, 9, 9, 4, 1, 5, 1, 4, 0, 6, 9, 7, 6, 2, 6, 6, 6, 2, 3, 0,
       3, 4, 4, 4, 6, 2, 3, 3, 6, 2, 4, 9, 9, 2, 0, 7, 9, 4, 2, 0, 1, 1,
       4, 6, 7, 1, 3, 4, 0, 2, 6, 6, 0, 6, 2, 3, 7, 2, 9, 4, 6, 2, 7, 6,
       0, 6, 8, 6, 5, 6, 3, 5, 0, 4, 0, 4, 0, 6, 7, 2, 0, 8, 6, 9, 4, 4,
       9, 6, 0, 1, 9, 4, 2, 5, 1, 0, 6, 3, 6, 1, 3, 9, 3, 4, 6, 2, 1, 0,
       0, 6, 4, 3, 7, 8, 1, 0, 6, 0, 1, 4, 0, 4, 3, 0, 1, 6, 4, 8, 6, 8,
       4, 4, 1, 9, 4, 8, 3, 1, 1, 1, 3, 1, 2, 8, 4, 5, 6, 1, 4, 0, 8, 4,
       2, 6, 9, 0, 8, 8, 9, 9, 3, 4, 1, 2, 4, 4, 4, 4, 4, 9, 4, 1, 6, 6,
       5, 9, 1, 5, 6, 1, 2, 8, 0, 4, 1, 6, 5, 1, 4,

In [458]:
df_es_1958['Topic'] = topic_results.argmax(axis=1)

In [459]:
df_es_1958.head()

page_text  Topic
0  potentes seguras económicas más barata económi...      2
1   ss sí jn cuatro días universidad católicaprod...      1
2  deténgalocon ar zl viene delapagevio más armad...      7
3  oelviernes rí selsábado viajessintrasbordo de ...      6
4  juntoalloroquelerecuerda sus no chesdegloria j...      5